version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: travel_itinerary
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travel_user -d travel_itinerary"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://travel_user:travel_password@db:5432/travel_itinerary
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
    volumes:
      - /home/khalid/.gcp/vertex-sa.json:/app/credentials.json
    env_file:
      - .env

volumes:
  postgres_data: